# Site settings

title: PSP Linkages Pt Nanoporous Foams
header-img: img/final header.png
email: mdekou3@gatech.edu
description: "define the process strusture property linkage of platinum nanoporous foams using data science tools"
baseurl: "/psp-linkages-Pt-foams"
url: "http://mariedekou.github.io"
github_username:  mariedekou
project_repository: psp-linkages-Pt-foams

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
